### ISSUE TITLE
Crashing with can't return acState of undefined

### ISSUE THREAD

**Issue by ChiffaN** [pdlove/homebridge-sensibo#16]
One of my pods has had the battery dead for some time now and it seems this causes an error: 

/usr/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:99
                                callback(data.result[i].acState);
TypeError: Cannot read property 'acState' of undefined
    at /usr/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:99:28
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:41:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I fixed this by adding a check for undefined before the callback, changing line 99 in sensiboapi.js to
if (data.result[i] !== undefined) callback(data.result[i].acState);

Seems to work now.

**Comment by frolov32** [comment]
Hello. 
Recently faced with the same problem. 
tried your method, but the result is that the temperature has a value of 16 degrees and the humidity is constantly 0. both values do not change.  maybe sensibo have changed the api?
@pdlove can you help us?

**Comment by frolov32** [comment]
I tried to change the battery. but it's not helping.

**Comment by django52** [comment]
hi, i´va the same error:
TypeError: Cannot read property 'acState' of undefined
    at /usr/local/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:104:28

**Comment by pbassham** [comment]
Me too.

**Comment by pbassham** [comment]
Here is my error

`[4/12/2017, 8:44:14 PM] Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:104
				callback(data.result[i].acState);
				                       ^

TypeError: Cannot read property 'acState' of undefined
    at /usr/local/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:104:28
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-sensibo/lib/sensiboapi.js:44:21)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`
